### PR TITLE
#28 : Unit test (ignored, no fix)

### PR DESCRIPTION
**Pull request by axel3rd**
A unit test for reproducing #28. No fix provided, problem is perhaps in **sslr-core** (usage).

### CODE REVIEW

**Comment by racodond** [comment]
See https://github.com/racodond/sonar-json-plugin/pull/30 instead

**Comment by axel3rd** [comment]
> See #30 instead

@racodond : ok for closing, but why not include it, this is a good real UT 😈

**Comment by racodond** [comment]
@axel3rd Don't worry :-) I included tests for both key pairs and values with even more lines: https://github.com/racodond/sonar-json-plugin/commit/ff0662ee6088deca665d4eb081a18bad15ec35c6#diff-42fede6877c8788798528f7c8a5c8019, https://github.com/racodond/sonar-json-plugin/commit/ff0662ee6088deca665d4eb081a18bad15ec35c6#diff-8b158248b161c502be4d72303f178588, https://github.com/racodond/sonar-json-plugin/commit/ff0662ee6088deca665d4eb081a18bad15ec35c6#diff-ca180030a0b97d18ca9f843213edc8d1R90, https://github.com/racodond/sonar-json-plugin/commit/ff0662ee6088deca665d4eb081a18bad15ec35c6#diff-5f4d6df4d368ef20b42e38f4c82c65a1R106 and https://github.com/racodond/sonar-json-plugin/commit/ff0662ee6088deca665d4eb081a18bad15ec35c6#diff-23603b3054b9b9f9c23c1b6c017518dfR72

**Comment by axel3rd** [comment]
ok :)

**Pull request closed without merging**
